name: Test

on:
  push:
    branches:
      - "**"

jobs:
  app-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build

  ws-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ws-server/package-lock.json

      - name: Install dependencies
        working-directory: ws-server
        run: npm ci

      - name: Type check
        working-directory: ws-server
        run: npx tsc --noEmit
